resource_group_name   = "rg-dxnb-new-dev"
location              = "Central India"
function_app_name     = "fa-dxnb-new-integration-dev"
function_storage_account_name = "sadxnbfunctionruntimedev"
storage_account_name  = "sadxnbnewdev"
xml_storage_account_name = "sadxnbxmlingestdev"
databricks_workspace_name = "dbw-dxnb-new-dev"
